apiVersion: v1
kind: Pod
metadata:
  name: login-secret-pod
spec:
  containers:
  - name: secret-demo-env
    image: busybox
    command: ["sh", "-c", "echo Username: $USERNAME && echo Password: $PASSWORD && sleep 3600"]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: login-secret
          key: username      # <- FIXED
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: login-secret
          key: password      # <- FIXED
  restartPolicy: Never
